spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qualitydb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true